apiVersion : apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: noisonnoiton/account:latest
          ports:
            - containerPort: 8180
---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  ports:
    - port: 8180
      targetPort: 8180
      name: account
  selector:
    app: account
